### ISSUE TITLE
Laravel 5.4 compatibility

### ISSUE THREAD

**Issue by RamonSmit** [dyaa/Laravel-pushover#15]
Hi there, 

Will there be in the future L5.4 compatibility?

I get the error message when updated to 5.4:
```
[2017-01-31 22:53:01] development.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::share() in /home/vagrant/Code/mdc/vendor/dyaa/pushover/src/Dyaa/Pushover/PushoverServiceProvider.php:23
Stack trace:
#0 /home/vagrant/Code/mdc/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(568): Dyaa\Pushover\PushoverServiceProvider->register()
#1 /home/vagrant/Code/mdc/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(Dyaa\Pushover\PushoverServiceProvider))
#2 /home/vagrant/Code/mdc/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(543): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /home/vagrant/Code/mdc/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /home/vagrant/Code/mdc/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /home/vagrant/Code/mdc/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(270): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /home/vagrant/Code/mdc/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(115): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /home/vagrant/Code/mdc/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}
```

It has something to do with: *share Method Removed*
https://laravel.com/docs/5.4/upgrade

Would you mind to take a look on this?

**Comment by Donny5300** [comment]
@dyaa i created a fix fit this, can you merge this one for us?

**Comment by Donny5300** [comment]
@RamonSmit 

Add this to your require in composer: `"dyaa/pushover": "dev-laravel5"`

Repositories in composer.json
```
"repositories": {
    "laravel-pushover": {
      "type": "vcs",
      "url": "https://github.com/Donny5300/Laravel-pushover.git"
    }
  }
```
